#!/usr/bin/env bash

[[ $# < 1 ]] && { >&2 echo "requires command"; exit 1; }

function gcloud_active_configuration() {
  gcloud config configurations list --filter=is_active=true --format=json | jq -r '.[0].name'
}

DEVBOX_NAME=${DEVBOX_NAME:-robyoung-dev1}
DEVBOX_GCLOUD=${DEVBOX_GCLOUD:-personal}
DEVBOX_PROJECT=$([ -n "$DEVBOX_PROJECT" ] && echo "--project=$DEVBOX_PROJECT" || echo "")
DEVBOX_ZONE=${DEVBOX_ZONE:-europe-west2-c}


command=$1
shift

case "$command" in
  create|up|down|ssh|scp|list)
    ;;
  *)
    >&2 echo "Unknown command $command"
    exit 1
    ;;
esac

active=$(gcloud_active_configuration)
if [[ $active != $DEVBOX_GCLOUD ]]; then
  gcloud config configurations activate $DEVBOX_GCLOUD
fi

case "$command" in
  create)
    gcloud compute instances create $DEVBOX_NAME \
      --zone=$DEVBOX_ZONE \
      $DEVBOX_PROJECT \
      --image-family=ubuntu-2104 \
      --image-project=ubuntu-os-cloud \
      --machine-type=n2-standard-16
    ;;
  up)
    gcloud beta compute instances resume --zone=$DEVBOX_ZONE $DEVBOX_PROJECT $DEVBOX_NAME
    ;;
  down)
    gcloud beta compute instances suspend --zone=$DEVBOX_ZONE $DEVBOX_PROJECT  $DEVBOX_NAME
    ;;
  ssh)
    if [[ $# > 0 ]]; then
      gcloud beta compute ssh --zone=$DEVBOX_ZONE $DEVBOX_NAME $DEVBOX_PROJECT -- "$@"
    else
      gcloud beta compute ssh --zone=$DEVBOX_ZONE $DEVBOX_NAME $DEVBOX_PROJECT -- tmux attach
    fi
    ;;
  scp)
    gcloud compute scp $1 $DEVBOX_NAME:${2:-}
    ;;
  list)
    gcloud compute instances list
    ;;
esac

if [[ $active != $DEVBOX_GCLOUD ]]; then
  gcloud config configurations activate $DEVBOX_GCLOUD
fi
