#!/usr/bin/env bash
#
# Auto-commit any changes to a git repository

git-autocommit-directory() {
  local directory=$1
  echo "auto committing $directory"
  pushd $directory
  git stash
  git pull
  git stash pop
  git saveall
  popd
}

if [[ $# > 0 ]]
then
  for directory in "$@"; do
    git-autocommit-directory $directory
  done
else
  git-autocommit-directory .
fi
