#!/usr/bin/env bash
#
# Auto-commit any changes to a git repository

[[ $# > 0 ]] || { >&2 echo "At least one path is required"; exit 1; }

while true; do
  for directory in "$@"; do
    echo "auto committing $directory"
    pushd $directory
    git stash
    git pull
    git stash pop
    git saveall
    popd
  done
  sleep 30
done
