#!/usr/bin/env zsh

op user list > /dev/null 2>&1 || eval $(op signin)

op item get ssh/robyoung-xps-2020 --format=json --fields=label=password | jq -r .value | clip

if type keychain >/dev/null 2>&1 ; then
  keychain -q --nogui $HOME/.ssh/id_ed25519
  source $HOME/.keychain/$HOST-sh  
else
  ssh-add ~/.ssh/id_ed25519
fi
