#!/bin/bash

tmux new-session -d -c ~/dev/turntown/data-rest-api -s turntown -n api
tmux new-window -c ~/dev/turntown/deployment -n charts
tmux new-window -c ~/dev/turntown/devops -n devops

tmux attach-session -t "turntown:0"
