#!/bin/bash

new-window() {
  tmux new-window -c ~/dev/github/robyoung/${1} -n ${1} ${2}
}


tmux new-session -d -c ~/Notes -s personal -n notes
new-window dotfiles


for name in "${@}"; do
  new-window ${name}
done

tmux attach-session
